[project]
name = "llama-proyecto-modelo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.142.2",
    "ollama>=0.6.3",
]

[project.scripts]
llama-proyecto-modelo = "llama_proyecto_modelo:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
